Ed25519 tests against NaCl
ltonetwork/seasalt pull request #21
Opened 2021-09-08 19:34 UTC by KaloyanTanev

2021-09-08 22:35 UTC, AndreaScorza approved these changes

2021-09-09 00:06 UTC, jasny requested changes
There should be a test for seeding a new key pair. The key pair should be the same for NaCl as for seasalt when using the same seed.

2021-09-09 00:06 UTC, jasny commented on pom.xml
> +        </dependency>
Scope should be set to `test`.
_(also for  other libs that are only used to test against like `org.web3j`.)_

2021-09-09 16:28 UTC, jasny approved these changes

2021-09-09 16:29 UTC, merged